name: 'update commit time'
on:
  push:
  pull-request:
jobs:
  job1:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    - name: 'test'
      run: |
        git config --global user.name 'bot'
        git config --global user.email 'bot@users.noreply.github.com'
        git commit -m "build action" -a
        git push
